theme: jekyll-theme-dinky
title: Ontology Engineering Class
description: Offered at RPI, Fall 2024
github:
  repo: https://github.com/tetherless-world/ontology-engineering
repository: tetherless-world/ontology-engineering
