PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX people: <https://spec.edmcouncil.org/fibo/ontology/FND/AgentsAndPeople/People/> 
PREFIX individuals: <https://tw.rpi.edu/ontology-engineering/oe2020/patient-guideline-recommender-individuals/> 
PREFIX pgo: <https://tw.rpi.edu/ontology-engineering/oe2020/patient-guideline-recommender/>
PREFIX fiboRoles: <https://spec.edmcouncil.org/fibo/ontology/FND/Parties/Roles/>
PREFIX fiboRelations: <https://spec.edmcouncil.org/fibo/ontology/FND/Relations/Relations/>
PREFIX lcc-lr: <https://www.omg.org/spec/LCC/Languages/LanguageRepresentation/>

SELECT DISTINCT ?guideline ?recommendation ?goalMet WHERE {
	?guideline a pgo:Guideline ;
		rdf:type ?restriction .

	# Find guideline restriction (?guideline appliesTo some ?cohort)
	?restriction a owl:Restriction ;
		owl:onProperty fiboRelations:appliesTo ;
		owl:someValuesFrom/owl:hasValue ?cohort .

	# Find cohort restraint (?cohort 'has member' some ?userConstraint)
	?cohort rdf:type ?p .
	?p a owl:Restriction ;
		owl:onProperty lcc-lr:hasMember ;
		owl:someValuesFrom ?userConstraint .

	# Only consider user constraints that restrict based on weight goal (?userConstraint 'equivalent to' hasWeightGoal *)
	?userConstraint owl:equivalentClass ?userFilt .
	?userFilt a owl:Restriction ;
		owl:onProperty pgo:hasWeightGoal .

	# Find target of recommendation
	?guideline pgo:recommends ?recommendation .
	# (recommendation recommends some ?recTarget)
	?recommendation a ?recRestriction .
	?recRestriction a owl:Restriction ;
		owl:onProperty pgo:recommends ;
		owl:someValuesFrom ?recTarget .
	
	# The following part requires the inferred axioms
	# Only consider guidelines that are applicable to the user
	individuals:NamirXiaUser a ?userConstraint .

	# Find if the user has satisfied the recommendation
	BIND(EXISTS {
		individuals:NamirXiaUser a ?recTarget .
	} as ?goalMet) .
}
