# Competency Question 1
#
# Goal:
#   Find all prerequisite courses for the Ontologies course
# 
# Explanation:
#   Specify the target course for which to find all prereqs;
#   Then find all courses for which the transitive hasRequiredPrerequisite property would apply
#   Output distinct course IRI along with its name

prefix oe2020-crs-rec: <https://tw.rpi.edu/ontology-engineering/oe2020/course-recommender/>
prefix oe2020-crs-rec-ind: <https://tw.rpi.edu/ontology-engineering/oe2020/course-recommender-individuals/>
prefix lcc-lr: <https://www.omg.org/spec/LCC/Languages/LanguageRepresentation/>
SELECT DISTINCT ?prerequisiteCourse ?prerequisiteCourseName
WHERE {  
  VALUES ?targetCourseTag { "CSCI-4340" }
  ?targetcourse oe2020-crs-rec:hasCourseCode [ lcc-lr:hasTag ?targetCourseTag ] ;
                oe2020-crs-rec:hasRequiredPrerequisite+ ?prerequisiteCourse .
  ?prerequisiteCourse oe2020-crs-rec:hasName ?prerequisiteCourseName .
}
