prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix xsd:   <http://www.w3.org/2001/XMLSchema#>

##
# banner rdfs:comment shouldn't be used for FIBO annotation.

SELECT DISTINCT ?error
WHERE
{
  ?s rdfs:comment ?o
  FILTER (REGEX (xsd:string (?s), "${NAMESPACE_REGEX}"))
  BIND (concat ("WARN: ", str(?s), " has an rdfs:comment annotation: ", str(?o)) AS ?error)
}
